app:
  jwtExpirationMs: 60000000
  jwtSecret: ${JWT_SECRET_KEY}
  dataLoader: true
server:
  port: 8084

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${DB_PASSWORD}
    url: ${DB_URL} #jdbc:postgresql://localhost:5432/reddit
    username: ${DB_USER} #compose-postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
    open-in-view: false
#logging:
#    level:
#        root: debug

